project:
  type: website
  # 新增：把构建结果放到 docs/，方便用 Pages 的 /docs 方式
  output-dir: docs

website:
  # 改成你自己的 Pages 域名（仓库名是 fall-2025-243）
  site-url: https://ziyu-ge.github.io/fall-2025-243
  # 声明Ziyu的仓库，页面会出现“Edit this page”等链接
  repo-url: https://github.com/Ziyu-Ge/fall-2025-243
  repo-actions: [source, edit, issue]

  sidebar:
    style: docked
    title: "Stat 243 (Ziyu’s Notes)"   # 改个小标题，和教授区分
    logo: assets/stat_bear.png
    logo-alt: "UC Berkeley Statistics logo"
    tools:
      - icon: github
        href: https://github.com/Ziyu-Ge/fall-2025-243    # 改为Ziyu的仓库
        aria-label: GitHub
    contents:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: schedule.qmd
        text: Schedule
      - href: office_hours.qmd
        text: Office Hours
      - section: "Units"
        contents:
          - href: units/unit1-intro.qmd
            text: "Unit 1 (UNIX intro)"
          - href: units/unit2-dataTech.qmd
            text: "Unit 2 (Data technologies)"
          - href: units/unit3-bash.qmd
            text: "Unit 3 (Bash shell)"
          - href: units/unit4-goodPractices.qmd
            text: "Unit 4 (Good practices)"
          - href: units/unit5-programming.qmd
            text: "Unit 5 (Programming)"
          - href: units/unit6-parallel.qmd
            text: "Unit 6 (Parallelization)"
          - href: units/unit7-bigData.qmd
            text: "Unit 7 (Databases)"
          - href: units/unit8-numbers.qmd
            text: "Unit 8 (Precision)"
          - href: units/unit9-sim.qmd
            text: "Unit 9 (Simulation)"
          - href: units/unit10-linalg.qmd
            text: "Unit 10 (Linear Algebra)"
          - href: units/unit11-optim.qmd
            text: "Unit 11 (Optimization)"
          - href: units/unit12-graphics.qmd
            text: "Unit 12 (Graphics)"
      - section: "Labs"
        contents:
          # 这些是现成的 HTML 文件（不是 qmd）
          - href: labs/lab0-setup.html
            text: "Lab 0 (Optional setup)"
          - href: labs/lab1-submission.html
            text: "Lab 1 (Quarto/Git/Submission)"
      - section: "Problem Sets"
        contents:
          - href: ps/ps1.qmd
          - href: ps/ps2.qmd
          - href: ps/ps3.qmd
          - href: ps/ps4.qmd
          - href: ps/ps5.qmd
          - href: ps/ps6.qmd
          - href: ps/ps7.qmd
          - href: ps/ps8.qmd
      - href: project/project.qmd
        text: Final Project
      - section: "How tos"
        contents:
          - howtos/accessPython.md
          - howtos/accessUnixCommandLine.md
          - howtos/installGit.md
          - howtos/installQuarto.md
          - howtos/vscode.md
          - howtos/submitPS.md
          - howtos/windowsAndLinux.md
      - href: license.qmd
        text: License
          
format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true
    include-in-header:
      file: siteimprove.html

execute:
  freeze: auto 
