project:
  type: website

website:
  site-url: https://stat243.berkeley.edu/fall-2024
  sidebar:
    style: docked
    title: "Stat 243"
    logo: assets/stat_bear.png
    tools:
      - icon: github
        href: https://github.com/berkeley-stat243/fall-2024
    contents:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: schedule.qmd
        text: Schedule
      - href: office_hours.qmd
        text: Office Hours
      - section: "Units"
        contents:
          - href: units/unit1-intro.qmd
            text: "Unit 1 (UNIX intro)"
          - href: units/unit2-dataTech.qmd
            text: "Unit 2 (Data technologies)"
          - href: units/unit3-bash.qmd
            text: "Unit 3 (Bash shell)"
          - href: units/unit4-goodPractices.qmd
            text: "Unit 4 (Good practices)"
      - section: "Labs"
        contents:
          - href: labs/lab0-setup.html
            text: "Lab 0 (Optional setup)"
          - href: labs/lab1-submission.html
            text: "Lab 1 (Quarto/Git/Submission)"
      - section: "Problem Sets"
        contents:
          - href: ps/ps1.qmd
          - href: ps/ps2.qmd
      - section: "How tos"
        contents:
          - howtos/accessPython.md
          - howtos/accessUnixCommandLine.md
          - howtos/installGit.md
          - howtos/installQuarto.md
          - howtos/submitPS.md
          - howtos/windowsAndLinux.md
      - href: license.qmd
        text: License
          
format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true

execute:
  freeze: auto

